# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
    - r: 3.2
    - r: 3.3
    - r: 3.4
    - r: 3.5
    - r: release
      env: R_CODECOV=true
      before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdow")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
        on:
          all_branches: true
          condition: '"$TRAVIS_BRANCH" == "pkgdown-travis" || -n "$TRAVIS_TAG"'
    - r: devel
    - os: osx
      osx_image: xcode9.3 #High Sierra
    - os: osx
      osx_image: xcode8.3 #Sierra
